// Re-export from the Prisma generated client (custom output: ../generated/client)
export { PrismaClient, Prisma } from '../generated/client';
export type {
  User,
  UserRole,
  Account,
  AccountUser,
  Location,
  Equipment,
  Technician,
  TechnicianCertification,
  TechnicianRegion,
  Job,
  JobEquipment,
  JobPart,
  JobPhoto,
  JobSignoff,
  Quote,
  QuoteLineItem,
  Contract,
  ContractProperty,
  Invoice,
  InvoiceLineItem,
  Payment,
  PaymentMethod,
  CommissionRule,
  CommissionEarning,
  Part,
  PartInventory,
  AuditLog,
  EmailInbox,
  EsignEnvelope,
  ErpSyncLog,
  CrmSyncLog,
  Notification,
  IdempotencyRecord,
} from '../generated/client';
export type {
  UserRoleEnum,
  EquipmentClass,
  JobType,
  JobStatus,
  QuoteStatus,
  ContractStatus,
  InvoiceStatus,
  PaymentStatus,
  EquipmentCondition,
  GenericStatus,
  TechType,
  TechAvailabilityStatus,
  JobPriority,
  SignoffStatus,
  ServiceType,
  Cadence,
  CommissionStatus,
  NotificationChannel,
  NotificationStatus,
  SyncStatus,
  EsignDocumentStatus,
  AccountUserRole,
} from '../generated/client';
